# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.live_activity_action_type import LiveActivityActionType

class TestLiveActivityActionType(unittest.TestCase):
    """LiveActivityActionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLiveActivityActionType(self):
        """Test LiveActivityActionType"""
        # inst = LiveActivityActionType()

if __name__ == '__main__':
    unittest.main()
