# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.changelog_entry import ChangelogEntry

class TestChangelogEntry(unittest.TestCase):
    """ChangelogEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangelogEntry:
        """Test ChangelogEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangelogEntry`
        """
        model = ChangelogEntry()
        if include_optional:
            return ChangelogEntry(
                id = '',
                platform = '',
                version = '',
                title = '',
                subtitle = '',
                hero_image_url = '',
                cta_title = '',
                published_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                items = [
                    activitysmith_openapi.models.changelog_item.ChangelogItem(
                        icon = '', 
                        title = '', 
                        body = '', 
                        image_url = '', 
                        accent_color = '', )
                    ]
            )
        else:
            return ChangelogEntry(
                id = '',
                platform = '',
                version = '',
                title = '',
                subtitle = '',
                hero_image_url = '',
                cta_title = '',
                published_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                items = [
                    activitysmith_openapi.models.changelog_item.ChangelogItem(
                        icon = '', 
                        title = '', 
                        body = '', 
                        image_url = '', 
                        accent_color = '', )
                    ],
        )
        """

    def testChangelogEntry(self):
        """Test ChangelogEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
