# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.live_activity_stream_delete_request import LiveActivityStreamDeleteRequest

class TestLiveActivityStreamDeleteRequest(unittest.TestCase):
    """LiveActivityStreamDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LiveActivityStreamDeleteRequest:
        """Test LiveActivityStreamDeleteRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LiveActivityStreamDeleteRequest`
        """
        model = LiveActivityStreamDeleteRequest()
        if include_optional:
            return LiveActivityStreamDeleteRequest(
                content_state = { },
                action = { },
                secondary_action = { },
                alert = { }
            )
        else:
            return LiveActivityStreamDeleteRequest(
        )
        """

    def testLiveActivityStreamDeleteRequest(self):
        """Test LiveActivityStreamDeleteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
