# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.update_app_icon_badge_count422_response import UpdateAppIconBadgeCount422Response

class TestUpdateAppIconBadgeCount422Response(unittest.TestCase):
    """UpdateAppIconBadgeCount422Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAppIconBadgeCount422Response:
        """Test UpdateAppIconBadgeCount422Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAppIconBadgeCount422Response`
        """
        model = UpdateAppIconBadgeCount422Response()
        if include_optional:
            return UpdateAppIconBadgeCount422Response(
                error = '',
                message = '',
                effective_channel_slugs = [
                    ''
                    ],
                code = 'badge_device_disconnected',
                badge = 0,
                devices_targeted = 56,
                devices_updated = 56,
                users_updated = 56,
                devices_notified = 56
            )
        else:
            return UpdateAppIconBadgeCount422Response(
                error = '',
                message = '',
                code = 'badge_device_disconnected',
                badge = 0,
                devices_updated = 56,
        )
        """

    def testUpdateAppIconBadgeCount422Response(self):
        """Test UpdateAppIconBadgeCount422Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
