# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.billing_blocked_error import BillingBlockedError

class TestBillingBlockedError(unittest.TestCase):
    """BillingBlockedError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingBlockedError:
        """Test BillingBlockedError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingBlockedError`
        """
        model = BillingBlockedError()
        if include_optional:
            return BillingBlockedError(
                error = 'trial_expired',
                message = '',
                trial_period = activitysmith_openapi.models.billing_blocked_error_trial_period.BillingBlockedError_trial_period(
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    ends_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                upgrade_url = ''
            )
        else:
            return BillingBlockedError(
                error = 'trial_expired',
                message = '',
                upgrade_url = '',
        )
        """

    def testBillingBlockedError(self):
        """Test BillingBlockedError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
