# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.live_activity_action import LiveActivityAction
from activitysmith_openapi.models.live_activity_action_type import LiveActivityActionType

class TestLiveActivityAction(unittest.TestCase):
    """LiveActivityAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LiveActivityAction:
        """Test LiveActivityAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LiveActivityAction`
        """
        model = LiveActivityAction()
        if include_optional:
            return LiveActivityAction(
                title = '',
                type = 'open_url',
                url = '',
                method = 'POST',
                body = { }
            )
        else:
            return LiveActivityAction(
                title = '',
                type = 'open_url',
                url = '',
        )
        """

    def testLiveActivityAction(self):
        """Test LiveActivityAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

    def test_open_url_allows_shortcuts_url(self):
        action = LiveActivityAction(
            title="Chat",
            type=LiveActivityActionType.OPEN_URL,
            url="shortcuts://run-shortcut?name=JARVIS",
        )

        self.assertEqual("shortcuts://run-shortcut?name=JARVIS", action.url)

    def test_webhook_rejects_shortcuts_url(self):
        with self.assertRaises(ValueError):
            LiveActivityAction(
                title="Chat",
                type=LiveActivityActionType.WEBHOOK,
                url="shortcuts://run-shortcut?name=JARVIS",
            )

if __name__ == '__main__':
    unittest.main()
