# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.health_response import HealthResponse

class TestHealthResponse(unittest.TestCase):
    """HealthResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HealthResponse:
        """Test HealthResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HealthResponse`
        """
        model = HealthResponse()
        if include_optional:
            return HealthResponse(
                ok = True,
                service = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                checks = [
                    activitysmith_openapi.models.health_check.HealthCheck(
                        name = 'database', 
                        status = 'ok', 
                        duration_ms = 0, )
                    ]
            )
        else:
            return HealthResponse(
                ok = True,
                service = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                checks = [
                    activitysmith_openapi.models.health_check.HealthCheck(
                        name = 'database', 
                        status = 'ok', 
                        duration_ms = 0, )
                    ],
        )
        """

    def testHealthResponse(self):
        """Test HealthResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
