# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.app_icon_badge_count_update_response import AppIconBadgeCountUpdateResponse

class TestAppIconBadgeCountUpdateResponse(unittest.TestCase):
    """AppIconBadgeCountUpdateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppIconBadgeCountUpdateResponse:
        """Test AppIconBadgeCountUpdateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppIconBadgeCountUpdateResponse`
        """
        model = AppIconBadgeCountUpdateResponse()
        if include_optional:
            return AppIconBadgeCountUpdateResponse(
                success = True,
                badge = 0,
                devices_updated = 56,
                users_updated = 56,
                devices_notified = 56,
                users_notified = 56,
                effective_channel_slugs = [
                    ''
                    ],
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AppIconBadgeCountUpdateResponse(
                success = True,
                badge = 0,
                devices_updated = 56,
                users_updated = 56,
                effective_channel_slugs = [
                    ''
                    ],
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testAppIconBadgeCountUpdateResponse(self):
        """Test AppIconBadgeCountUpdateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
