# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.activity_metric import ActivityMetric

class TestActivityMetric(unittest.TestCase):
    """ActivityMetric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivityMetric:
        """Test ActivityMetric
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivityMetric`
        """
        model = ActivityMetric()
        if include_optional:
            return ActivityMetric(
                label = '0',
                value = 0,
                unit = ''
            )
        else:
            return ActivityMetric(
                label = '0',
                value = 0,
        )
        """

    def testActivityMetric(self):
        """Test ActivityMetric"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
