# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.api.public_api import PublicApi


class TestPublicApi(unittest.TestCase):
    """PublicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PublicApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_health(self) -> None:
        """Test case for get_api_health

        Get API Health
        """
        pass

    def test_list_public_changelog_entries(self) -> None:
        """Test case for list_public_changelog_entries

        List Public Changelog Entries
        """
        pass


if __name__ == '__main__':
    unittest.main()
