# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.api.app_icon_badges_api import AppIconBadgesApi


class TestAppIconBadgesApi(unittest.TestCase):
    """AppIconBadgesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppIconBadgesApi()

    def tearDown(self) -> None:
        pass

    def test_update_app_icon_badge_count(self) -> None:
        """Test case for update_app_icon_badge_count

        Set App Icon Badge Count
        """
        pass


if __name__ == '__main__':
    unittest.main()
