# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.live_activity_stream_put_response import LiveActivityStreamPutResponse

class TestLiveActivityStreamPutResponse(unittest.TestCase):
    """LiveActivityStreamPutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LiveActivityStreamPutResponse:
        """Test LiveActivityStreamPutResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LiveActivityStreamPutResponse`
        """
        model = LiveActivityStreamPutResponse()
        if include_optional:
            return LiveActivityStreamPutResponse(
                success = True,
                operation = 'started',
                stream_key = '',
                activity_id = '',
                previous_activity_id = '',
                devices_notified = 56,
                devices_queued = 56,
                users_notified = 56,
                effective_channel_slugs = [
                    ''
                    ],
                tags = [
                    'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM0'
                    ],
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return LiveActivityStreamPutResponse(
                success = True,
                operation = 'started',
                stream_key = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testLiveActivityStreamPutResponse(self):
        """Test LiveActivityStreamPutResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
