# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.app_icon_badge_count_update_error import AppIconBadgeCountUpdateError

class TestAppIconBadgeCountUpdateError(unittest.TestCase):
    """AppIconBadgeCountUpdateError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppIconBadgeCountUpdateError:
        """Test AppIconBadgeCountUpdateError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppIconBadgeCountUpdateError`
        """
        model = AppIconBadgeCountUpdateError()
        if include_optional:
            return AppIconBadgeCountUpdateError(
                error = '',
                code = 'badge_device_disconnected',
                message = '',
                badge = 0,
                devices_targeted = 56,
                devices_updated = 56,
                users_updated = 56,
                devices_notified = 56,
                effective_channel_slugs = [
                    ''
                    ]
            )
        else:
            return AppIconBadgeCountUpdateError(
                error = '',
                code = 'badge_device_disconnected',
                message = '',
                badge = 0,
                devices_updated = 56,
        )
        """

    def testAppIconBadgeCountUpdateError(self):
        """Test AppIconBadgeCountUpdateError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
