# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.push_notification_webhook_method import PushNotificationWebhookMethod

class TestPushNotificationWebhookMethod(unittest.TestCase):
    """PushNotificationWebhookMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPushNotificationWebhookMethod(self):
        """Test PushNotificationWebhookMethod"""
        # inst = PushNotificationWebhookMethod()

if __name__ == '__main__':
    unittest.main()
