# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.live_activity_start_request import LiveActivityStartRequest

class TestLiveActivityStartRequest(unittest.TestCase):
    """LiveActivityStartRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LiveActivityStartRequest:
        """Test LiveActivityStartRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LiveActivityStartRequest`
        """
        model = LiveActivityStartRequest()
        if include_optional:
            return LiveActivityStartRequest(
                content_state = activitysmith_openapi.models.content_state_start.ContentStateStart(
                    title = '', 
                    subtitle = '', 
                    number_of_steps = 1, 
                    current_step = 0, 
                    percentage = 0, 
                    value = 1.337, 
                    upper_limit = 1.337, 
                    duration_seconds = 1.337, 
                    counts_down = True, 
                    is_running = True, 
                    metrics = [
                        activitysmith_openapi.models.activity_metric.ActivityMetric(
                            label = '0', 
                            value = null, 
                            unit = '', 
                            color = 'lime', )
                        ], 
                    message = '0', 
                    icon = activitysmith_openapi.models.live_activity_alert_icon.LiveActivityAlertIcon(
                        symbol = '0', 
                        color = 'lime', ), 
                    badge = activitysmith_openapi.models.live_activity_alert_badge.LiveActivityAlertBadge(
                        title = '0', ), 
                    type = 'segmented_progress', 
                    color = 'lime', 
                    step_color = 'lime', 
                    step_colors = [
                        'lime'
                        ], ),
                action = {
                    'key' : null
                    },
                secondary_action = {
                    'key' : null
                    },
                alert = activitysmith_openapi.models.alert_payload.AlertPayload(
                    title = '', 
                    body = '', ),
                target = activitysmith_openapi.models.channel_target.ChannelTarget(
                    channels = [
                        ''
                        ], ),
                tags = [
                    'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM0'
                    ]
            )
        else:
            return LiveActivityStartRequest(
                content_state = activitysmith_openapi.models.content_state_start.ContentStateStart(
                    title = '', 
                    subtitle = '', 
                    number_of_steps = 1, 
                    current_step = 0, 
                    percentage = 0, 
                    value = 1.337, 
                    upper_limit = 1.337, 
                    duration_seconds = 1.337, 
                    counts_down = True, 
                    is_running = True, 
                    metrics = [
                        activitysmith_openapi.models.activity_metric.ActivityMetric(
                            label = '0', 
                            value = null, 
                            unit = '', 
                            color = 'lime', )
                        ], 
                    message = '0', 
                    icon = activitysmith_openapi.models.live_activity_alert_icon.LiveActivityAlertIcon(
                        symbol = '0', 
                        color = 'lime', ), 
                    badge = activitysmith_openapi.models.live_activity_alert_badge.LiveActivityAlertBadge(
                        title = '0', ), 
                    type = 'segmented_progress', 
                    color = 'lime', 
                    step_color = 'lime', 
                    step_colors = [
                        'lime'
                        ], ),
        )
        """

    def testLiveActivityStartRequest(self):
        """Test LiveActivityStartRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
