# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.no_recipients_error import NoRecipientsError

class TestNoRecipientsError(unittest.TestCase):
    """NoRecipientsError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NoRecipientsError:
        """Test NoRecipientsError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NoRecipientsError`
        """
        model = NoRecipientsError()
        if include_optional:
            return NoRecipientsError(
                error = '',
                message = '',
                effective_channel_slugs = [
                    ''
                    ]
            )
        else:
            return NoRecipientsError(
                error = '',
                message = '',
        )
        """

    def testNoRecipientsError(self):
        """Test NoRecipientsError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
