# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.live_activity_end_request import LiveActivityEndRequest

class TestLiveActivityEndRequest(unittest.TestCase):
    """LiveActivityEndRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LiveActivityEndRequest:
        """Test LiveActivityEndRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LiveActivityEndRequest`
        """
        model = LiveActivityEndRequest()
        if include_optional:
            return LiveActivityEndRequest(
                activity_id = '',
                content_state = activitysmith_openapi.models.content_state_end.ContentStateEnd(
                    title = '', 
                    subtitle = '', 
                    number_of_steps = 1, 
                    current_step = 0, 
                    percentage = 0, 
                    value = 1.337, 
                    upper_limit = 1.337, 
                    duration_seconds = 1.337, 
                    counts_down = True, 
                    is_running = True, 
                    metrics = [
                        activitysmith_openapi.models.activity_metric.ActivityMetric(
                            label = '0', 
                            value = null, 
                            unit = '', 
                            color = 'lime', )
                        ], 
                    message = '0', 
                    icon = activitysmith_openapi.models.live_activity_alert_icon.LiveActivityAlertIcon(
                        symbol = '0', 
                        color = 'lime', ), 
                    badge = activitysmith_openapi.models.live_activity_alert_badge.LiveActivityAlertBadge(
                        title = '0', ), 
                    type = 'segmented_progress', 
                    color = 'lime', 
                    step_color = 'lime', 
                    step_colors = [
                        'lime'
                        ], 
                    auto_dismiss_minutes = 0, ),
                action = {
                    'key' : null
                    },
                secondary_action = {
                    'key' : null
                    }
            )
        else:
            return LiveActivityEndRequest(
                activity_id = '',
                content_state = activitysmith_openapi.models.content_state_end.ContentStateEnd(
                    title = '', 
                    subtitle = '', 
                    number_of_steps = 1, 
                    current_step = 0, 
                    percentage = 0, 
                    value = 1.337, 
                    upper_limit = 1.337, 
                    duration_seconds = 1.337, 
                    counts_down = True, 
                    is_running = True, 
                    metrics = [
                        activitysmith_openapi.models.activity_metric.ActivityMetric(
                            label = '0', 
                            value = null, 
                            unit = '', 
                            color = 'lime', )
                        ], 
                    message = '0', 
                    icon = activitysmith_openapi.models.live_activity_alert_icon.LiveActivityAlertIcon(
                        symbol = '0', 
                        color = 'lime', ), 
                    badge = activitysmith_openapi.models.live_activity_alert_badge.LiveActivityAlertBadge(
                        title = '0', ), 
                    type = 'segmented_progress', 
                    color = 'lime', 
                    step_color = 'lime', 
                    step_colors = [
                        'lime'
                        ], 
                    auto_dismiss_minutes = 0, ),
        )
        """

    def testLiveActivityEndRequest(self):
        """Test LiveActivityEndRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
