# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.push_notification_request import PushNotificationRequest

class TestPushNotificationRequest(unittest.TestCase):
    """PushNotificationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PushNotificationRequest:
        """Test PushNotificationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PushNotificationRequest`
        """
        model = PushNotificationRequest()
        if include_optional:
            return PushNotificationRequest(
                title = '',
                message = '',
                subtitle = '',
                media = 'https:/',
                redirection = 'shortcuts:/',
                actions = [
                    {
                        'key' : null
                        }
                    ],
                payload = None,
                badge = 56,
                sound = '',
                target = activitysmith_openapi.models.channel_target.ChannelTarget(
                    channels = [
                        ''
                        ], ),
                tags = [
                    'gB:9JLe6iL71-aa-.Ctq:dcsc.3-8:1gAa8Xa6u61ArrlGpCQjkQVRmfnjddwcDM0'
                    ]
            )
        else:
            return PushNotificationRequest(
                title = '',
        )
        """

    def testPushNotificationRequest(self):
        """Test PushNotificationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
