# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.push_notification_action_type import PushNotificationActionType

class TestPushNotificationActionType(unittest.TestCase):
    """PushNotificationActionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPushNotificationActionType(self):
        """Test PushNotificationActionType"""
        # inst = PushNotificationActionType()

if __name__ == '__main__':
    unittest.main()
