# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from activitysmith_openapi.models.changelog_item import ChangelogItem

class TestChangelogItem(unittest.TestCase):
    """ChangelogItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangelogItem:
        """Test ChangelogItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangelogItem`
        """
        model = ChangelogItem()
        if include_optional:
            return ChangelogItem(
                icon = '',
                title = '',
                body = '',
                image_url = '',
                accent_color = ''
            )
        else:
            return ChangelogItem(
                title = '',
                body = '',
        )
        """

    def testChangelogItem(self):
        """Test ChangelogItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
