# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from activitysmith_openapi.models.alert_payload import AlertPayload
from activitysmith_openapi.models.channel_target import ChannelTarget
from activitysmith_openapi.models.content_state_start import ContentStateStart
from activitysmith_openapi.models.live_activity_action import LiveActivityAction
from typing import Optional, Set
from typing_extensions import Self

class LiveActivityStartRequest(BaseModel):
    """
    Start a new Live Activity. The response includes activity_id for later update and end calls.
    """ # noqa: E501
    content_state: ContentStateStart
    action: Optional[LiveActivityAction] = None
    secondary_action: Optional[LiveActivityAction] = Field(default=None, description="Optional secondary action button. Supported for alert, progress, and segmented_progress Live Activities. Uses the same open_url, shortcuts://, and webhook shapes as action.")
    alert: Optional[AlertPayload] = None
    target: Optional[ChannelTarget] = None
    __properties: ClassVar[List[str]] = ["content_state", "action", "secondary_action", "alert", "target"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LiveActivityStartRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of content_state
        if self.content_state:
            _dict['content_state'] = self.content_state.to_dict()
        # override the default output from pydantic by calling `to_dict()` of action
        if self.action:
            _dict['action'] = self.action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of secondary_action
        if self.secondary_action:
            _dict['secondary_action'] = self.secondary_action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of alert
        if self.alert:
            _dict['alert'] = self.alert.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LiveActivityStartRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "content_state": ContentStateStart.from_dict(obj["content_state"]) if obj.get("content_state") is not None else None,
            "action": LiveActivityAction.from_dict(obj["action"]) if obj.get("action") is not None else None,
            "secondary_action": LiveActivityAction.from_dict(obj["secondary_action"]) if obj.get("secondary_action") is not None else None,
            "alert": AlertPayload.from_dict(obj["alert"]) if obj.get("alert") is not None else None,
            "target": ChannelTarget.from_dict(obj["target"]) if obj.get("target") is not None else None
        })
        return _obj


