# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LiveActivityColor(str, Enum):
    """
    LiveActivityColor
    """

    """
    allowed enum values
    """
    LIME = 'lime'
    GREEN = 'green'
    CYAN = 'cyan'
    BLUE = 'blue'
    PURPLE = 'purple'
    MAGENTA = 'magenta'
    RED = 'red'
    ORANGE = 'orange'
    YELLOW = 'yellow'
    GRAY = 'gray'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LiveActivityColor from a JSON string"""
        return cls(json.loads(json_str))


