# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PushInterruptionLevel(str, Enum):
    """
    How urgently iOS presents the notification. `passive` arrives quietly in the notification list without sound or lighting up the screen. `active` is normal delivery and the default when omitted. `time-sensitive` can break through Focus and Scheduled Summary when the user allows Time Sensitive Notifications for ActivitySmith.
    """

    """
    allowed enum values
    """
    PASSIVE = 'passive'
    ACTIVE = 'active'
    TIME_MINUS_SENSITIVE = 'time-sensitive'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PushInterruptionLevel from a JSON string"""
        return cls(json.loads(json_str))


