# coding: utf-8

"""
    ActivitySmith API

    Send push notifications and Live Activities to your own devices via a single API key.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PushNotificationWebhookMethod(str, Enum):
    """
    PushNotificationWebhookMethod
    """

    """
    allowed enum values
    """
    GET = 'GET'
    POST = 'POST'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PushNotificationWebhookMethod from a JSON string"""
        return cls(json.loads(json_str))


